name: Format, Lint and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  format-lint-test:
    name: Format, Lint and Test
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        project: [client, server, website]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install dependencies
      working-directory: ./${{ matrix.project }}
      run: npm install

    - name: Run format check
      working-directory: ./${{ matrix.project }}
      run: npm run format -- --check

    - name: Run lint
      working-directory: ./${{ matrix.project }}
      run: npm run lint

    - name: Run tests
      working-directory: ./${{ matrix.project }}
      run: npm run test